@ECHO OFF
REM Meant to be called AFTER bootstrap.cmd

IF NOT DEFINED PROJECT_ROOT GOTO USAGE
IF NOT EXIST tmp\vcpkg\installed\%PROJECT_TARGET_TRIPLET% GOTO USAGE
GOTO RUN_CMAKE

:USAGE
ECHO Please "CALL .\bootstrap.cmd" before .\configure.cmd
GOTO :EOF

:RUN_CMAKE
@ECHO ON
cmake ^
-G "%PROJECT_BUILDSYSTEM%" ^
-B "%PROJECT_BUILDDIR%" ^
-S "%PROJECT_ROOT%" ^
-DCMAKE_BUILD_TYPE=%PROJECT_BUILDTYPE% ^
-DBUILD_SHARED_LIBS=ON ^
-DBUILD_SXE_SDK=ON
