@ECHO OFF

IF NOT DEFINED JAVA_HOME (
	CALL "%ENVSETUP_DIR%\.cmd\java-environment.cmd"
	IF NOT DEFINED JAVA_HOME (
		ECHO JAVA_HOME is not set!
		GOTO :eof
	)
)
ECHO Your JAVA_HOME is "%JAVA_HOME%"

IF NOT DEFINED ANDROID_HOME (
	CALL "%ENVSETUP_DIR%\.cmd\android-environment.cmd"
	IF NOT DEFINED ANDROID_HOME (
		ECHO ANDROID_HOME is not set!
		GOTO :eof
	)
)
ECHO Your ANDROID_HOME is "%ANDROID_HOME%"

ECHO Your XDG_DATA_HOME is "%XDG_DATA_HOME%"
ECHO Your XDG_CONFIG_HOME is "%XDG_CONFIG_HOME%"
ECHO Your XDG_CACHE_HOME is "%XDG_CACHE_HOME%"

